### ISSUE TITLE
cacli train stuck on starting training run

### ISSUE THREAD

**Issue by aditya9026** [cloud-annotations/cloud-annotations-cli#11]
```ruby
⠼ Starting training run...(node:8475) UnhandledPromiseRejectionWarning: StatusCodeError: 401 - {"trace":"xxxxxxxxxxxxxxxxxxxxxxxxxxx","errors":[{"code":"authorization_rejected","message":"Unable to get /v3/wml_instances/xxxxxxxxxxxxxx/authz [401]: {\"trace\":\"xxxxxxxxxxxxxxxxxxx\",\"errors\":[{\"code\":\"authorization_rejected\",\"message\":\"Instance xxxxxxxxxxxxxxxx is not found\",\"target\":{\"type\":\"header\",\"name\":\"Authorization\"}}]}","target":{"type":"header","name":"Authorization"}}]}
at new StatusCodeError (/home/aditya/.nvm/versions/node/v10.16.0/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/errors.js:32:15)
at Request.plumbing.callback (/home/aditya/.nvm/versions/node/v10.16.0/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:104:33)
at Request.RP$callback [as _callback] (/home/aditya/.nvm/versions/node/v10.16.0/lib/node_modules/cloud-annotations/node_modules/request-promise-core/lib/plumbing.js:46:31)
.
.
.starting training run....
```

**Comment by aditya9026** [comment]
updated to the latest version fixed the error for me!
